#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(f"NumPy Version: {np.__version__}")

NumPy Version: 1.23.5


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.empty(10)
print(null_vector)

[8.64684703e-312 2.27270197e-322 0.00000000e+000 0.00000000e+000
 0.00000000e+000 1.16095484e-028 3.65093134e+233 4.25117084e-096
 9.80058441e+252 1.23971686e+224]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
np.random.seed(15)
arr = np.random.random(12)
print(arr)
print(f"The Size of the array in memory: {arr.size * arr.itemsize}")

[0.8488177  0.17889592 0.05436321 0.36153845 0.27540093 0.53000022
 0.30591892 0.30447436 0.11174128 0.24989901 0.9176299  0.26414685]

The Size of the array in memory: 96


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
help(np.add)

np.add?

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector = np.zeros(10, dtype = np.int8)
null_vector[4] = 1
print(null_vector)

[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr = np.arange(10, 21)
print(f"Before Reversing: {arr}")

arr = arr[::-1]
print(f"After  Reversing: {arr}")


Before Reversing: [10 11 12 13 14 15 16 17 18 19 20]
After  Reversing: [20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
arr_3x3 = np.arange(0, 9).reshape(3, 3)
print(arr_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr = np.array([1,2,0,0,4,0])
print(f"Indices of non-zero: {arr.nonzero()}")

Indices of non-zero: (array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
arr_identity = np.eye(3)
print(arr_identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
np.random.seed(20)
random_val_arr = np.random.random((3,3, 3))
print(random_val_arr)

[[[0.5881308  0.89771373 0.89153073]
  [0.81583748 0.03588959 0.69175758]
  [0.37868094 0.51851095 0.65795147]]

 [[0.19385022 0.2723164  0.71860593]
  [0.78300361 0.85032764 0.77524489]
  [0.03666431 0.11669374 0.7512807 ]]

 [[0.23921822 0.25480601 0.85762553]
  [0.94977903 0.56168686 0.17878052]
  [0.77025193 0.49238104 0.63125307]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
np.random.seed(15)
random_10x10_arr = np.random.random((10,10))
print(random_10x10_arr)
print("=" * 30)
print(f"Min Number: {np.round(np.min(random_10x10_arr), 5)}")
print(f"Max Number: {np.round(np.max(random_10x10_arr), 5)}")

[[0.8488177  0.17889592 0.05436321 0.36153845 0.27540093 0.53000022
  0.30591892 0.30447436 0.11174128 0.24989901]
 [0.9176299  0.26414685 0.71777369 0.86571503 0.80707948 0.21055058
  0.16724303 0.04670639 0.03942231 0.20023081]
 [0.9985434  0.37278698 0.76051027 0.47347444 0.50971531 0.94503842
  0.10944665 0.46509316 0.14155526 0.53834876]
 [0.29899866 0.53774522 0.66562754 0.3643288  0.62301862 0.64272489
  0.41998182 0.40324243 0.39042033 0.40618952]
 [0.07966611 0.0568312  0.07833091 0.69567781 0.02915896 0.49949242
  0.13263432 0.03075563 0.63948943 0.44599815]
 [0.97460664 0.32976593 0.19542482 0.68404621 0.35109886 0.77103611
  0.7917995  0.44387459 0.2688283  0.02390442]
 [0.37133257 0.09773088 0.72752255 0.45944443 0.52049647 0.68456904
  0.4252903  0.60347306 0.82384911 0.45187126]
 [0.8879452  0.22039954 0.10682265 0.01201013 0.9179414  0.63656621
  0.21976204 0.54755243 0.92079967 0.87566594]
 [0.12759215 0.30365374 0.29529657 0.56910504 0.74341963 0.33001519
  0.60785231

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
np.random.seed(8)
random_vector = np.random.random(30)
print(f"Mean of Vector: {np.round(np.mean(random_vector), 6)}")

Mean of Vector: 0.50559


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
one_border_arr = np.ones((10, 10), dtype= np.int8)
one_border_arr[1:-1, 1:-1] = 0
print(one_border_arr)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
arr = np.ones((6, 6))
arr = np.pad(arr, 2)
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))

nan
False
False
nan
True


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
arr = np.arange(0, 25).reshape(5,5)
print("Before:\n", arr)
for i in range(1, arr.shape[0]):
    for j in range(arr.shape[0]):
        if i == j:
            arr[i, j-1] = i

print("\nAfter:\n", arr)


Before:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

After:
 [[ 0  1  2  3  4]
 [ 1  6  7  8  9]
 [10  2 12 13 14]
 [15 16  3 18 19]
 [20 21 22  4 24]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
checkerboard_pattern = np.ones((8,8))
# checkerboard_pattern[0::2, 0::2] = 0
print(checkerboard_pattern)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print(np.unravel_index(100 - 1 , (6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
checkerboard = np.tile([[1,0], [0,1]], (4,4))
print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

<ipython-input-27-b9f1a6f5df9c>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
rgba_martrix = np.dtype([("red", np.ubyte, (1,)),
                  ("green", np.ubyte, (1,)),
                  ("bule", np.ubyte, (1,)),
                  ("alpha", np.ubyte, (1,))])

print(rgba_martrix)

[('red', 'u1', (1,)), ('green', 'u1', (1,)), ('bule', 'u1', (1,)), ('alpha', 'u1', (1,))]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
matrix_5x3 = np.arange(1, 16).reshape(5,3)
matrix_3x2 = np.arange(1, 7).reshape(3,2)
print(f"5x3 Matrix:\n {matrix_5x3}")
print()
print(f"3x2 Matrix:\n {matrix_3x2}")
print()
print(f"Dot Product Result {matrix_5x3.shape[0]}X{matrix_3x2.shape[-1]} Matrix:\n{matrix_5x3.dot(matrix_3x2)}")

5x3 Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

3x2 Matrix:
 [[1 2]
 [3 4]
 [5 6]]

Dot Product Result 5X2 Matrix:
[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
one_d_arr = np.arange(0, 15)
one_d_arr[3+1: 8] = one_d_arr[3+1: 8] * -1

print(f"After Negating: {one_d_arr}")

After Negating: [ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z = np.array([1,2,3,5,4,7])

print(2 << z >> 2)

[ 1  2  4 16  8 64]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))

print(np.array(0) // np.array(0))

print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-85-72dab2b1b7c8>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-85-72dab2b1b7c8>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
arr = np.arange(1.5, 15.5).reshape(2, 7)
print(f"Before Rounding: \n{arr}")
arr = np.round(arr)
print(f"After  Rounding: \n{arr}")

Before Rounding: 
[[ 1.5  2.5  3.5  4.5  5.5  6.5  7.5]
 [ 8.5  9.5 10.5 11.5 12.5 13.5 14.5]]
After  Rounding: 
[[ 2.  2.  4.  4.  6.  6.  8.]
 [ 8. 10. 10. 12. 12. 14. 14.]]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
np.random.seed(12)
arr_1 = np.random.randint(1, 25, size=(3, 4))
arr_2 = np.random.randint(5, 25, size=(3, 4))
print(arr_1)
print()
print(arr_2)
print()
common_elements = np.intersect1d(arr_1, arr_2)
print(common_elements)

[[12  7 18  3]
 [ 4  4 13 17]
 [23 18 21  6]]

[[18  7 16 15]
 [ 5 13 17 18]
 [23  8  9  8]]

[ 7 13 17 18 23]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-26-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today     = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(f"Today: {today}")
print(f"Yestraday: {yesterday}")
print(f"Tomorrow: {tomorrow}")

Today: 2023-09-26
Yestraday: 2023-09-25
Tomorrow: 2023-09-27


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
print("July Month Calendr")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July Month Calendr
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
arr_A = np.arange(1, 5)
arr_B = np.arange(3, 7)

print(f"{((arr_A + arr_B) * (-arr_A / 2))}")

[ -2.  -6. -12. -20.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
np.random.seed(30)
random_array = np.random.rand(6)*100

print(random_array)
print(f"1) {np.trunc(random_array)}") # remove fraction
print(f"2) {np.floor(random_array)}") # get integer number
print(f"3) {np.fix(random_array)}") # get integer number
print(f"4) {random_array.astype(int)}") # remove fraction and get the integer

[64.41435361 38.07484896 66.30479053 16.36507261 96.26078137 34.66618404]
1) [64. 38. 66. 16. 96. 34.]
2) [64. 38. 66. 16. 96. 34.]
3) [64. 38. 66. 16. 96. 34.]
4) [64 38 66 16 96 34]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
arr = np.tile(np.arange(0, 5), 5).reshape(5,5)
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generator():
    l =[]
    for i in range(10):
        l.append(i)
    return l

arr = np.array(generator())
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
vector_0_1 = np.linspace(0, 1, 12)[1:-1]
print(np.round(vector_0_1, 4))

[0.0909 0.1818 0.2727 0.3636 0.4545 0.5455 0.6364 0.7273 0.8182 0.9091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
np.random.seed(26)
arr = np.sort(np.random.randint(1, 26, 10))
print(arr)

[ 1  2  3  5  7  7 14 17 20 22]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
np.random.seed(15)
arr = np.random.randint(1, 15, size = (3, 2))
sum_arr = np.add.reduce(arr.flatten()) # converting the array to vector and sum all elements
print(arr)
print(f"Sum By Rows: {np.add.reduce(arr)}")
print(f"Sum By Columns: \n{np.add.reduce(arr, 1).reshape(3, 1)}")
print(f"Total Sum: {sum_arr}")

[[ 9  6]
 [13  6]
 [ 8  1]]
Sum By Rows: [30 13]
Sum By Columns: 
[[15]
 [19]
 [ 9]]
Total Sum: 43


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
# Test 1
np.random.seed(51)
A = np.random.randint(1, 15, size = (3, 2))
B = np.random.randint(1, 15, size = (3, 2))

# Test 2
np.random.seed(51)
A = np.array([[1, 4, 50, 6], [5, 56, 34, 32]])
B = np.array([[1, 4, 50, 6], [5, 56, 34, 32]])

print(A)
print()
print(B)
print("Equal" if np.array_equal(A, B) else "Not Equal")

[[ 1  4 50  6]
 [ 5 56 34 32]]

[[ 1  4 50  6]
 [ 5 56 34 32]]
Equal


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
np.random.seed(46)
arr = np.random.randint(1, 15, size = (2, 2))
print(arr)

arr.flags.writeable = False
try:
    arr[0] = 30
    print(arr)
except:
    print("Can't Change The Value Immutable Array")



[[14  6]
 [ 9  5]]
Can't Change The Value Immutable Array


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
# Hint Link: https://www.mathsisfun.com/polar-cartesian-coordinates.html
# https://numpy.org/doc/stable/reference/generated/numpy.arctan.html

np.random.seed(16)
cartesian_arr = np.random.random((10, 2))
x_cords = cartesian_arr[:, 0]
y_cords = cartesian_arr[:, 1]
r_power_2 = np.power(x_cords, 2) +  np.power(y_cords, 2)
r = np.sqrt(r_power_2).reshape(10, 1)
angle_ceta = np.arctan2(y_cords, x_cords).reshape(10, 1)
polar_arr = np.append(r, angle_ceta, 1)
print("Polar Coordinates:")
print("  r  \t     angle_ceta")
print(polar_arr)
# polar_arr = np.concatenate(r, angle_ceta)


Polar Coordinates:
  r  	     angle_ceta
[[0.56882228 1.16739402]
 [0.55258631 0.08261853]
 [0.42413488 0.55385166]
 [0.70792069 0.23339827]
 [0.94363501 1.49620167]
 [0.56905141 0.13748952]
 [0.73980835 0.2158523 ]
 [0.38571428 0.86468809]
 [0.83714254 0.58786042]
 [0.49588853 1.12221185]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
np.random.seed(10)
random_v = np.random.randint(1, 20, 10)
print(random_v)
max_index = random_v.argmax()
random_v[max_index] = 0
print(random_v)

[10  5 16  1 18 17 18  9 10  1]
[10  5 16  1  0 17 18  9 10  1]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
arr_x = np.arange(5)
arr_y = arr_x + 0.5
arr_c = np.round(1.0 / np.subtract.outer(arr_x, arr_y), 4)
print(arr_x)
print()
print(arr_y)
print()
print(arr_c)


[0 1 2 3 4]

[0.5 1.5 2.5 3.5 4.5]

[[-2.     -0.6667 -0.4    -0.2857 -0.2222]
 [ 2.     -2.     -0.6667 -0.4    -0.2857]
 [ 0.6667  2.     -2.     -0.6667 -0.4   ]
 [ 0.4     0.6667  2.     -2.     -0.6667]
 [ 0.2857  0.4     0.6667  2.     -2.    ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
int_dtype = [np.int8, np.int32, np.int64]
float_dtype = [np.float32, np.float64]

for d in int_dtype:
    print(f"Datatype: {d}")
    print(f"Min Value: {np.iinfo(d).min}")
    print(f"Max Value: {np.iinfo(d).max}")
    print("-"*20)


for d in float_dtype:
    print(f"Datatype: {d}")
    print(f"Min Value: {np.finfo(d).min}")
    print(f"Max Value: {np.finfo(d).max}")
    print("-"*20)

Datatype: <class 'numpy.int8'>
Min Value: -128
Max Value: 127
--------------------
Datatype: <class 'numpy.int32'>
Min Value: -2147483648
Max Value: 2147483647
--------------------
Datatype: <class 'numpy.int64'>
Min Value: -9223372036854775808
Max Value: 9223372036854775807
--------------------
Datatype: <class 'numpy.float32'>
Min Value: -3.4028234663852886e+38
Max Value: 3.4028234663852886e+38
--------------------
Datatype: <class 'numpy.float64'>
Min Value: -1.7976931348623157e+308
Max Value: 1.7976931348623157e+308
--------------------


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
arr = np.random.randint(10, 45, size = (10, 10))
print(arr)

[[10 24 19 36 27 15 11 22 32 10]
 [17 10 36 29 28 17 15 39 11 38]
 [16 31 33 37 13 16 44 37 18 18]
 [20 30 14 33 11 17 18 34 31 33]
 [28 29 24 42 33 33 44 42 27 42]
 [42 28 14 12 25 17 43 15 20 38]
 [27 18 16 26 30 13 22 22 11 28]
 [33 34 18 26 31 29 41 13 44 35]
 [24 19 17 32 43 41 44 15 24 22]
 [26 38 30 28 19 44 16 40 13 17]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
np.random.seed(54)
arr = np.arange(30)
print("Vector:")
print(arr)

rand_val = np.random.random()*30
print("Value to compare:")
print(rand_val)

index = (np.abs(arr-rand_val)).argmin()
print(f"The Cloasest Value is: {arr[index]}")

Vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Value to compare:
12.605489014223215
The Cloasest Value is: 13


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
# ****** Hint Linke *****
# https://www.mathsisfun.com/algebra/distance-2-points.html
np.random.seed(51)

arr = np.random.randint(10, 101, size= (100, 2))
point_x = arr[:, 0].reshape(1, 100)
point_y = arr[:, 1].reshape(1, 100)

X = np.power(point_x - np.transpose(point_x), 2)
Y = np.power(point_y - np.transpose(point_y), 2)

distance = np.sqrt(X + Y)
print(distance)
print(f"Size of The Result Arrays: {distance.size}")

[[ 0.         58.24946352 41.67733197 ... 72.83543094 11.70469991
   7.21110255]
 [58.24946352  0.         60.         ... 63.19810124 48.70318265
  55.97320788]
 [41.67733197 60.          0.         ... 34.43835072 33.52610923
  34.4818793 ]
 ...
 [72.83543094 63.19810124 34.43835072 ...  0.         62.36986452
  65.7951366 ]
 [11.70469991 48.70318265 33.52610923 ... 62.36986452  0.
   7.28010989]
 [ 7.21110255 55.97320788 34.4818793  ... 65.7951366   7.28010989
   0.        ]]
Size of The Result Arrays: 10000


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
arr_f = np.arange(1.211212, 13.2323254, dtype = np.float32)
print(arr_f)
print(arr_f.astype(np.int32))

[ 1.211212   2.211212   3.2112117  4.2112117  5.2112117  6.2112117
  7.211211   8.211211   9.211211  10.211211  11.211211  12.211211
 13.21121  ]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
txt_array = """1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11"""

f = open("numpy_arr.csv", "w")
f.write(txt_array)
f.close()

arr = np.genfromtxt("numpy_arr.csv", delimiter=",")
print(arr)
print("\nComverting nan Value into 0\n")
print(arr.astype(np.int8))


[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]

Comverting nan Value into 0

[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
# https://www.scaler.com/topics/what-is-the-equivalent-of-enum-in-numpy/

np.random.seed(105)
arr = np.random.randint(1, 10, size = (3, 3))
print(f"Matrix With Shape {arr.shape[0]}x{arr.shape[1]}:\n{arr}")
print()
print("Elements of the array with their indices:")
for index, value in np.ndenumerate(arr):
    print(f"{index} -> {value}")



Matrix With Shape 3x3:
[[1 6 7]
 [5 1 1]
 [5 1 5]]

Elements of the array with their indices:
(0, 0) -> 1
(0, 1) -> 6
(0, 2) -> 7
(1, 0) -> 5
(1, 1) -> 1
(1, 2) -> 1
(2, 0) -> 5
(2, 1) -> 1
(2, 2) -> 5


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
arr = np.full((5, 5), 1)
print(arr)
random_element = np.random.randint(10, 30)
random_row = np.random.randint(0, arr.shape[0])
random_col = np.random.randint(0, arr.shape[1])
arr[random_row, random_col] = random_element
print()
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[ 1  1  1  1  1]
 [23  1  1  1  1]
 [ 1  1  1  1  1]
 [ 1  1  1  1  1]
 [ 1  1  1  1  1]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
np.random.seed(5)
arr = np.random.randint(0, 10, size = (5, 5))
print(f"Matrix Before Subtracting:\n{arr}")

mean_for_rows = np.mean(arr, 1).reshape(5, 1)
arr = arr - mean_for_rows

print()
print(f"Matrix After  Subtracting:\n{arr}")

Matrix Before Subtracting:
[[3 6 6 0 9]
 [8 4 7 0 0]
 [7 1 5 7 0]
 [1 4 6 2 9]
 [9 9 9 1 2]]

Matrix After  Subtracting:
[[-1.8  1.2  1.2 -4.8  4.2]
 [ 4.2  0.2  3.2 -3.8 -3.8]
 [ 3.  -3.   1.   3.  -4. ]
 [-3.4 -0.4  1.6 -2.4  4.6]
 [ 3.   3.   3.  -5.  -4. ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
np.random.seed(5)
arr = np.random.randint(0, 10, size = (5, 5))
print(f"Matrix Before Sorting:\n{arr}")

print(arr[arr[:,1].argsort()])

Matrix Before Sorting:
[[3 6 6 0 9]
 [8 4 7 0 0]
 [7 1 5 7 0]
 [1 4 6 2 9]
 [9 9 9 1 2]]

[2 1 3 0 4]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [2]:
np.random.seed(20)
arr = np.random.randint(0, 8, size = (4, 4))
print(arr)
m = arr != 0
print(m)
print("Has No Null Values" if m.all() else "Has Null Values")

[[3 2 7 7]
 [4 2 1 4]
 [3 6 7 2]
 [0 6 0 5]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [False  True False  True]]
Has Null Values


#### 61. Find the nearest value from a given value in an array (★★☆)

In [3]:
arr = np.arange(0, 25).reshape(5,5)
val = np.random.random()*26
index = (np.abs(val - arr)).argmin()
print(arr, val)

pos = np.unravel_index(index, (5,5))
print(f"Nearest Value: {arr[pos[0], pos[1]]}")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 17.10673810452914
Nearest Value: 17


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [5]:
np.random.seed(108)
arr_1 = np.random.randint(1, 10, size = (1, 3))
arr_2 = np.random.randint(1, 10, size = (3, 1))
print(arr_1)
print()
print(arr_2)
print()
print(arr_1  + arr_2)


[[4 8 2]]

[[7]
 [3]
 [5]]

[[11 15  9]
 [ 7 11  5]
 [ 9 13  7]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[6 6 4 1 0 7 6 4 2 6 3 1 1 0 8 6 3 2 6 2]
[3. 4. 4. 3. 3. 1. 7. 2. 2. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [12]:
X = np.array([1,2,3,4,5,6])
I = np.array([1,3,9,3,4,1])
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [20]:
arr = np.random.randint(0,10,(3,4,3,4))
print(arr.sum(axis=(-2,-1)))

[[53 47 52 48]
 [53 51 53 46]
 [55 48 44 73]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [45]:
arr_1 = np.arange(1,10).reshape(3,3)
arr_2 = np.arange(10,19).reshape(3,3)
print(arr_1)
print()
print(arr_2)
print()
dot_product = np.dot(arr_1, arr_2)
print(f"Dot Product of 2 matrix: \n{dot_product}")
print(f"Dot Product Diagonal: \n{dot_product.diagonal()}")


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10 11 12]
 [13 14 15]
 [16 17 18]]

Dot Product of 2 matrix: 
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
Dot Product Diagonal: 
[ 84 216 366]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [72]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
arr = arr.reshape(5,1)
arr_zeros = np.zeros((arr.shape[0], 3), dtype= np.int8)
arr = np.concatenate((arr, arr_zeros), axis = 1)
arr = arr.flatten()[0:-3]
print(arr)

[1 2 3 4 5]
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [32]:
nums1 = np.random.randint(1, 15, size = (5,5,3))
nums2 = np.random.randint(1, 15, size = (5,5)).reshape(5,5,1)
print("Multiplication array:")
print(nums1 * nums2)


Original array:
[[[ 72 126   9]
  [  2  13  11]
  [ 90 130  10]
  [  6  36   6]
  [ 42  18  48]]

 [[117  65 169]
  [104  78 104]
  [ 42  66   6]
  [ 60  72  12]
  [ 55  30  50]]

 [[108  72  99]
  [110 140  30]
  [ 24  24  12]
  [126  36  45]
  [ 96 108 144]]

 [[140  70  14]
  [ 21  21  77]
  [  2   4  14]
  [ 36   9  63]
  [  6  33   3]]

 [[  8  52  36]
  [ 20  28  12]
  [112  72  80]
  [  5  15  10]
  [ 18  18   4]]]


#### 72. How to swap two rows of an array? (★★★)

In [6]:
arr = np.array([[1, 2, 3, 4], [5, 6, 8, 7], [10, 40, 68, 27], [3, 4, 9, 6]])
print("Before Swapping")
print(arr)
print()
temp =np.copy(arr[0, :])
arr[0, :] = arr[2, :]
arr[2, :] = temp
print("After  Swapping")
print(arr)


Before Swapping
[[ 1  2  3  4]
 [ 5  6  8  7]
 [10 40 68 27]
 [ 3  4  9  6]]

After  Swapping
[[10 40 68 27]
 [ 5  6  8  7]
 [ 1  2  3  4]
 [ 3  4  9  6]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)